// DVP-TSK-860: the shell nav registry. Nav derives from the live Enceladus
// caps snapshot (src/shell/capsSnapshot.json, regenerated by
// scripts/regen-caps-snapshot.mjs) plus the PermissionManifest. Display only:
// the server stays the authority on every action.
import { defineNavRegistry } from '@io-kit/shell'
import type { CapsFile, NavItemInput, PermissionManifest } from '@io-kit/shell'
import capsSnapshot from './capsSnapshot.json'

/** Group that may execute (write) Enceladus actions; the escalation decide
 *  gates stay server-side (three gates, untouched). */
export const EXECUTE_GROUP = 'io-dev-admin'

export const PERMISSIONS: PermissionManifest = {
  version: '2026.10.1',
  default: 'allow',
  rules: { 'execute.*': { groups: [EXECUTE_GROUP], mode: 'disable' } },
}

const PLANNED = { status: 'planned' as const, owner: 'io', plannedSince: '2026-10-10' }

export const NAV_ITEMS: NavItemInput[] = [
  { id: 'projects', label: 'Projects', route: '/projects' },
  { id: 'feed', label: 'Feed', route: '/feed' },
  { id: 'docs', label: 'Docs', route: '/docs' },
  { id: 'skills', label: 'Skill Library', route: '/skills' },
  { id: 'governance', label: 'Governance', route: '/governance' },
  { id: 'changelog', label: 'Changelog', route: '/changelog' },
  { id: 'coordination', label: 'Coordination', route: '/coordination' },
  // ENC-TSK-O40: the escalations decision surface (the only approve/deny path).
  { id: 'escalations', label: 'Escalations', route: '/escalations' },
  // Former PlaceholderRoute stubs: planned, with an owner, no route until built.
  { id: 'component-registry', label: 'Component registry', route: '/component-registry', placement: 'secondary', ...PLANNED },
  { id: 'deployments', label: 'Deployment manager', route: '/deployments', placement: 'secondary', ...PLANNED },
  { id: 'access-tokens', label: 'Access tokens', route: '/access-tokens', placement: 'secondary', ...PLANNED },
  { id: 'terminal-sessions', label: 'Terminal sessions', route: '/terminal-sessions', placement: 'secondary', ...PLANNED },
]

export const NAV_REGISTRY = defineNavRegistry(capsSnapshot as unknown as CapsFile, PERMISSIONS, {
  items: NAV_ITEMS,
  stack: 'enceladus',
})
